# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --max-complexity=10
          - --max-line-length=88
        additional_dependencies: [flake8-quotes]
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
