name: Flake8

on:
  push:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: pip
        cache-dependency-path: requirements*.txt

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements-dev.txt

    - name: Run flake8
      run: |
        echo "::add-matcher::.github/matchers/flake8.json"
        pre-commit run flake8 --all-files
        echo "::remove-matcher owner=flake8::"
