name: Release

on:
  release:
    types: [published]
  push:
  pull_request:

jobs:
  release:
    uses: ./.github/workflows/release-shared.yml
    with:
      github_event_name: ${{ github.event_name }}
    permissions:
      id-token: write
