name: Type check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ty:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.14

    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        cache-suffix: ${{ steps.setup_python.outputs.python-version }}

    - name: Install System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq -y --no-install-recommends libxmlsec1-dev

    - name: Type check ty
      run: uv run --all-extras ty check --output-format=github

  pyright:
    runs-on: ubuntu-24.04
    env:
      PYTHONUNBUFFERED: 1

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.14

    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        cache-suffix: ${{ steps.setup_python.outputs.python-version }}

    - name: Install System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq -y --no-install-recommends libxmlsec1-dev

    - name: Type check with pyright
      run: uv run --all-extras pyright

  mypy:
    runs-on: ubuntu-24.04
    env:
      PYTHONUNBUFFERED: 1

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.14

    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        cache-suffix: ${{ steps.setup_python.outputs.python-version }}

    - name: Install System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq -y --no-install-recommends libxmlsec1-dev

    - name: Type check with mypy
      run: uv run --all-extras mypy social_core
